environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - yarn --version
  - yarn

build_script:
  - yarn test+build

cache:
  - "%LOCALAPPDATA%\\Yarn"

services:
  - mssql2017