cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'

install:
  - ps: Install-Product node 8
  - node --version
  - npm --version
  - yarn --version
  - yarn install

before_build:
  - yarn test

build_script:
  - yarn build

services:
  - mssql2017