environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - yarn --version
  - yarn

test_script:
  - yarn test

build_script:
  - yarn build

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'

services:
  - mssql2017