init:
  - ps: Set-WinSystemLocale ko-KR
  - tzutil /s "Korea Standard Time"
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer
  - ps: Start-Sleep -s 5

services:
  - mssql2008r2sp2

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%/Yarn'

install:
  # Update build version depending on package.json version.
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: $env:package_name = (Get-Content -Raw -Path package.json | ConvertFrom-Json).name
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

  - sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "SELECT * FROM sys.syslanguages"
  - sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "SELECT * FROM sys.fn_helpcollations() WHERE name like '%Korean%'"
  - sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "SET LANGUAGE Korean"
  -

  # Install Node.js.
  - ps: Install-Product node 8

  # Display versions.
  - node --version
  - npm --version
  - yarn --version

  # Update dependencies.
  - yarn install

before_build:
  - yarn test

build_script:
  - yarn build