init:
  - tzutil /s "Korea Standard Time"
  - ps: Set-WinSystemLocale ko-KR
  - ps: Restart-Computer
cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'

install:
  - ps: Install-Product node 8
  - node --version
  - npm --version
  - yarn --version
  - yarn install

before_build:
  - cmd: yarn test

build_script:
  - yarn build

services:
  - mssql2017