init:
  - ps: Set-WinSystemLocale ko-KR
  - tzutil /s "Korea Standard Time"
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer
  - ps: Start-Sleep -s 5

services:
  - mssql2008r2sp2

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%/Yarn'

install:
  # Update build version depending on package.json version.
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: $env:package_name = (Get-Content -Raw -Path package.json | ConvertFrom-Json).name
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

  # Install Node.js.
  - ps: Install-Product node 8

  # Install Yarn
  - ps: Write-Host "Installing Yarn!"
  - ps: (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
  - ps: cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart

  # Display versions.
  - node --version
  - npm --version
  - yarn --version

  # Update dependencies.
  - yarn install

before_build:
  - yarn test || SET EXITVAL=1

build_script:
  - yarn build || SET EXITVAL=1