cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%/Yarn'

init:
  - ps: Set-WinSystemLocale ko-KR
  - cmd: tzutil /s "Korea Standard Time"
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer
  - ps: Start-Sleep -s 5

install:
  # Update build version depending on package.json version.
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: $env:package_name = (Get-Content -Raw -Path package.json | ConvertFrom-Json).name
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

  # Install Node.js.
  - ps: Install-Product node 8

  # Install Yarn
  - ps: Write-Host "Installing Yarn!"
  - ps: (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
  - ps: cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart

  # Update dependencies.
  - cmd: yarn install

build: off

test_script:
  # Display versions.
  - cmd: node --version
  - cmd: npm --version
  - cmd: yarn --version

  - cmd: SET EXITVAL=0
  - cmd: powershell %cd%\appveyor.ps1 SQL2008R2SP2
  - cmd: yarn test || SET EXITVAL=1
  - cmd: net stop MSSQL$SQL2008R2SP2
  - cmd: EXIT /B %EXITVAL%
